function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(1)=1/(1+params(14));
    GAMMA=(1-params(1)*(1-params(4)))/(params(1)*params(5));
    KAPA=(params(11)/(GAMMA^(params(5)/(params(5)-1))*params(10)))^(1/(params(10)+(-(params(5)*params(10)))/(params(5)-1)-1));
    params(16)=((1-params(5)-params(10))*((GAMMA*KAPA^(-params(10)))^(1/(params(5)-1)))^params(5)*KAPA^params(10))^(1/(params(7)-1));
    params(17)=KAPA*params(16);
    params(18)=(GAMMA*KAPA^(-params(10)))^(1/(params(5)-1))*params(16);
    params(20)=params(18)^params(5)*params(17)^params(10)*params(16)^(1-params(5)-params(10));
    params(23)=params(20)-params(4)*params(18)-params(14)*params(15)-params(11)*params(17);
    params(19)=params(4)*params(18);
    params(24)=(params(20)-params(19)-params(23))/params(20);
    params(25)=0;
    params(26)=1;
    params(21)=params(15);
    params(22)=1;
    ys_(7)=log(params(17));
    ys_(4)=log(params(16));
    ys_(3)=log(params(18));
    ys_(1)=log(params(20));
    ys_(2)=log(params(23));
    ys_(6)=log(params(22));
    ys_(9)=params(21);
    ys_(8)=log(params(19));
    ys_(5)=log(params(26));
    ys_(10)=params(24);
    ys_(11)=params(25);
    % Auxiliary equations
end
