function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(6)=1/(1+params(4));
    KAPA=((1/params(6)-(1-params(2)))/params(3))^(1/(params(3)-1));
    params(12)=((1-params(3))*KAPA^params(3))^(1/(params(7)-1));
    params(13)=KAPA*params(12);
    params(15)=params(13)^params(3)*params(12)^(1-params(3));
    params(17)=params(15)-params(2)*params(13)-params(4)*params(5);
    params(14)=params(2)*params(13);
    params(18)=(params(15)-params(14)-params(17))/params(15);
    params(19)=0;
    params(20)=1;
    params(16)=params(5);
    ys_(3)=log(params(12));
    ys_(5)=log(params(13));
    ys_(1)=log(params(15));
    ys_(2)=log(params(17));
    ys_(7)=params(16);
    ys_(4)=log(params(14));
    ys_(6)=log(params(20));
    ys_(8)=params(18);
    ys_(9)=params(19);
    % Auxiliary equations
end
