%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clearvars -global
clear_persistent_variables(fileparts(which('dynare')), false)
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'RBC_SOE_TP3';
M_.dynare_version = '6.3';
oo_.dynare_version = '6.3';
options_.dynare_version = '6.3';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(1,1);
M_.exo_names_tex = cell(1,1);
M_.exo_names_long = cell(1,1);
M_.exo_names(1) = {'u_a'};
M_.exo_names_tex(1) = {'{u_a}'};
M_.exo_names_long(1) = {'shock'};
M_.endo_names = cell(9,1);
M_.endo_names_tex = cell(9,1);
M_.endo_names_long = cell(9,1);
M_.endo_names(1) = {'y'};
M_.endo_names_tex(1) = {'y'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'c'};
M_.endo_names_tex(2) = {'c'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'k'};
M_.endo_names_tex(3) = {'{k}'};
M_.endo_names_long(3) = {'capital'};
M_.endo_names(4) = {'h'};
M_.endo_names_tex(4) = {'{h}'};
M_.endo_names_long(4) = {'hours'};
M_.endo_names(5) = {'a'};
M_.endo_names_tex(5) = {'{a}'};
M_.endo_names_long(5) = {'TFP'};
M_.endo_names(6) = {'ii'};
M_.endo_names_tex(6) = {'{i}'};
M_.endo_names_long(6) = {'investment'};
M_.endo_names(7) = {'d'};
M_.endo_names_tex(7) = {'{d}'};
M_.endo_names_long(7) = {'net debt position'};
M_.endo_names(8) = {'tby'};
M_.endo_names_tex(8) = {'{tb/y}'};
M_.endo_names_long(8) = {'trade balance-output ratio'};
M_.endo_names(9) = {'cay'};
M_.endo_names_tex(9) = {'{ca/y}'};
M_.endo_names_long(9) = {'current account-output ratio'};
M_.endo_partitions = struct();
M_.param_names = cell(20,1);
M_.param_names_tex = cell(20,1);
M_.param_names_long = cell(20,1);
M_.param_names(1) = {'BETA'};
M_.param_names_tex(1) = {'{\beta}'};
M_.param_names_long(1) = {'discount factor'};
M_.param_names(2) = {'PSI'};
M_.param_names_tex(2) = {'{\psi}'};
M_.param_names_long(2) = {'portfolio adjustement cost'};
M_.param_names(3) = {'SIGMA'};
M_.param_names_tex(3) = {'{\sigma}'};
M_.param_names_long(3) = {'risk aversion'};
M_.param_names(4) = {'DELTA'};
M_.param_names_tex(4) = {'{\delta}'};
M_.param_names_long(4) = {'depreciation rate'};
M_.param_names(5) = {'ALPHA'};
M_.param_names_tex(5) = {'{\alpha}'};
M_.param_names_long(5) = {'capital share'};
M_.param_names(6) = {'RHO'};
M_.param_names_tex(6) = {'{\rho}'};
M_.param_names_long(6) = {'persistence TFP shock'};
M_.param_names(7) = {'OMEGA'};
M_.param_names_tex(7) = {'{\omega}'};
M_.param_names_long(7) = {'labor disutility'};
M_.param_names(8) = {'PHI'};
M_.param_names_tex(8) = {'{\phi}'};
M_.param_names_long(8) = {'investment costs'};
M_.param_names(9) = {'ETA'};
M_.param_names_tex(9) = {'{\eta}'};
M_.param_names_long(9) = {'sd of productivity innovations'};
M_.param_names(10) = {'r_int'};
M_.param_names_tex(10) = {'{r^*}'};
M_.param_names_long(10) = {'international interest rate'};
M_.param_names(11) = {'D_BAR'};
M_.param_names_tex(11) = {'{\bar{d}}'};
M_.param_names_long(11) = {'average level of debt'};
M_.param_names(12) = {'h_ss'};
M_.param_names_tex(12) = {'{h_ss}'};
M_.param_names_long(12) = {'steady state labor'};
M_.param_names(13) = {'k_ss'};
M_.param_names_tex(13) = {'{k_ss}'};
M_.param_names_long(13) = {'steady state capital'};
M_.param_names(14) = {'ii_ss'};
M_.param_names_tex(14) = {'{i_ss}'};
M_.param_names_long(14) = {'steady state interest rate'};
M_.param_names(15) = {'y_ss'};
M_.param_names_tex(15) = {'{y_ss}'};
M_.param_names_long(15) = {'steady state output'};
M_.param_names(16) = {'d_ss'};
M_.param_names_tex(16) = {'{d_ss}'};
M_.param_names_long(16) = {'steady state debt'};
M_.param_names(17) = {'c_ss'};
M_.param_names_tex(17) = {'{h_ss}'};
M_.param_names_long(17) = {'steady state consumption'};
M_.param_names(18) = {'tby_ss'};
M_.param_names_tex(18) = {'{tby_ss}'};
M_.param_names_long(18) = {'steady state trade balance to output ratio'};
M_.param_names(19) = {'cay_ss'};
M_.param_names_tex(19) = {'{\bar{d}}'};
M_.param_names_long(19) = {'steady state current account to output ratio'};
M_.param_names(20) = {'a_ss'};
M_.param_names_tex(20) = {'{\bar{d}}'};
M_.param_names_long(20) = {'steady state productivity'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 9;
M_.param_nbr = 20;
M_.orig_endo_nbr = 9;
M_.aux_vars = [];
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.eq_nbr = 9;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 4 0;
 0 5 13;
 1 6 14;
 0 7 15;
 2 8 16;
 0 9 0;
 3 10 0;
 0 11 0;
 0 12 0;]';
M_.nstatic = 4;
M_.nfwrd   = 2;
M_.npred   = 1;
M_.nboth   = 2;
M_.nsfwrd   = 4;
M_.nspred   = 3;
M_.ndynamic   = 5;
M_.dynamic_tmp_nbr = [12; 8; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'resource constraint' ;
  2 , 'name' , 'Marginal productivity of labor' ;
  3 , 'name' , 'Choice of debt' ;
  4 , 'name' , 'Choice of capital' ;
  5 , 'name' , 'Production Function' ;
  6 , 'name' , 'Evolution of capital' ;
  7 , 'name' , 'Definition of current account as a ratio of gdp' ;
  8 , 'name' , 'Definition of trade balance as a ratio of gdp' ;
  9 , 'name' , 'Stochastic process for produtivity' ;
};
M_.mapping.y.eqidx = [1 5 7 8 ];
M_.mapping.c.eqidx = [1 3 4 8 ];
M_.mapping.k.eqidx = [1 2 4 5 6 8 ];
M_.mapping.h.eqidx = [2 3 4 5 ];
M_.mapping.a.eqidx = [2 4 5 9 ];
M_.mapping.ii.eqidx = [6 8 ];
M_.mapping.d.eqidx = [1 3 7 ];
M_.mapping.tby.eqidx = [8 ];
M_.mapping.cay.eqidx = [7 ];
M_.mapping.u_a.eqidx = [9 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 1;
M_.block_structure.block(1).mfs = 1;
M_.block_structure.block(1).equation = [ 9];
M_.block_structure.block(1).variable = [ 5];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 2;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 ];
M_.block_structure.block(2).Simulation_Type = 8;
M_.block_structure.block(2).endo_nbr = 5;
M_.block_structure.block(2).mfs = 5;
M_.block_structure.block(2).equation = [ 5 1 4 2 3];
M_.block_structure.block(2).variable = [ 1 7 3 4 2];
M_.block_structure.block(2).is_linear = false;
M_.block_structure.block(2).NNZDerivatives = 23;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [2 3 6 7 8 9 10 13 14 15 ];
M_.block_structure.block(3).Simulation_Type = 3;
M_.block_structure.block(3).endo_nbr = 1;
M_.block_structure.block(3).mfs = 1;
M_.block_structure.block(3).equation = [ 6];
M_.block_structure.block(3).variable = [ 6];
M_.block_structure.block(3).is_linear = false;
M_.block_structure.block(3).NNZDerivatives = 1;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(4).Simulation_Type = 1;
M_.block_structure.block(4).endo_nbr = 2;
M_.block_structure.block(4).mfs = 2;
M_.block_structure.block(4).equation = [ 8 7];
M_.block_structure.block(4).variable = [ 8 9];
M_.block_structure.block(4).is_linear = true;
M_.block_structure.block(4).NNZDerivatives = 2;
M_.block_structure.block(4).bytecode_jacob_cols_to_sparse = [3 4 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.block(2).g1_sparse_rowval = int32([2 1 2 3 4 1 2 2 5 2 3 1 3 4 5 2 3 5 3 3 5 3 5 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([2 3 3 3 3 6 6 7 7 8 8 9 9 9 9 10 10 10 13 14 14 15 15 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 1 2 6 6 6 8 10 12 16 19 19 19 20 22 24 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(4).g1_sparse_rowval = int32([]);
M_.block_structure.block(4).g1_sparse_colval = int32([]);
M_.block_structure.block(4).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 5 1 7 3 4 2 6 8 9];
M_.block_structure.equation_reordered = [ 9 5 1 4 2 3 6 8 7];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 1 3;
 1 7;
 2 3;
 4 3;
 5 3;
 6 3;
 7 7;
 8 3;
 9 5;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 7;
 2 4;
 2 5;
 3 2;
 3 4;
 3 7;
 4 2;
 4 3;
 4 4;
 5 1;
 5 4;
 5 5;
 6 3;
 6 6;
 7 1;
 7 7;
 7 9;
 8 1;
 8 2;
 8 3;
 8 6;
 8 8;
 9 5;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 3 2;
 3 4;
 4 2;
 4 3;
 4 4;
 4 5;
];
M_.block_structure.dyn_tmp_nbr = 28;
M_.state_var = [5 7 3 ];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(9, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(20, 1);
M_.endo_trends = struct('deflator', cell(9, 1), 'log_deflator', cell(9, 1), 'growth_factor', cell(9, 1), 'log_growth_factor', cell(9, 1));
M_.NNZDerivatives = [42; -1; -1; ];
M_.dynamic_g1_sparse_rowval = int32([1 2 4 5 6 8 9 1 7 1 5 7 8 1 3 4 8 1 4 6 8 2 3 4 5 2 5 9 6 8 1 3 7 8 7 3 4 4 3 4 4 9 ]);
M_.dynamic_g1_sparse_colval = int32([3 3 3 3 3 3 5 7 7 10 10 10 10 11 11 11 11 12 12 12 12 13 13 13 13 14 14 14 15 15 16 16 16 17 18 20 20 21 22 22 23 28 ]);
M_.dynamic_g1_sparse_colptr = int32([1 1 1 7 7 8 8 10 10 10 14 18 22 26 29 31 34 35 36 36 38 39 41 42 42 42 42 42 43 ]);
M_.lhs = {
'exp(y)+d'; 
'exp(h)^(OMEGA-1)'; 
'(exp(c)-exp(h)^OMEGA/OMEGA)^(-SIGMA)'; 
'(exp(c)-exp(h)^OMEGA/OMEGA)^(-SIGMA)*(1+PHI*(exp(k)-exp(k(-1))))'; 
'exp(y)'; 
'exp(k)'; 
'cay'; 
'tby'; 
'a'; 
};
M_.static_tmp_nbr = [8; 6; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 1;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 7];
M_.block_structure_stat.block(1).variable = [ 9];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 9];
M_.block_structure_stat.block(2).variable = [ 5];
M_.block_structure_stat.block(3).Simulation_Type = 6;
M_.block_structure_stat.block(3).endo_nbr = 5;
M_.block_structure_stat.block(3).mfs = 5;
M_.block_structure_stat.block(3).equation = [ 3 4 5 2 1];
M_.block_structure_stat.block(3).variable = [ 2 4 1 3 7];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 6];
M_.block_structure_stat.block(4).variable = [ 6];
M_.block_structure_stat.block(5).Simulation_Type = 1;
M_.block_structure_stat.block(5).endo_nbr = 1;
M_.block_structure_stat.block(5).mfs = 1;
M_.block_structure_stat.block(5).equation = [ 8];
M_.block_structure_stat.block(5).variable = [ 8];
M_.block_structure_stat.variable_reordered = [ 9 5 2 4 1 3 7 6 8];
M_.block_structure_stat.equation_reordered = [ 7 9 3 4 5 2 1 6 8];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 7;
 2 3;
 2 4;
 2 5;
 3 2;
 3 4;
 3 7;
 4 2;
 4 3;
 4 4;
 4 5;
 5 1;
 5 3;
 5 4;
 5 5;
 6 3;
 6 6;
 7 9;
 8 1;
 8 2;
 8 6;
 8 8;
 9 5;
];
M_.block_structure_stat.tmp_nbr = 18;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 2 5 1 2 3 4 3 5 2 3 4 5 1 5 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 1 1 2 2 2 2 3 3 4 4 4 4 5 5 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 4 8 10 14 16 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([]);
M_.static_g1_sparse_rowval = int32([1 5 8 1 3 4 8 1 2 4 5 6 2 3 4 5 2 4 5 9 6 8 1 3 8 7 ]);
M_.static_g1_sparse_colval = int32([1 1 1 2 2 2 2 3 3 3 3 3 4 4 4 4 5 5 5 5 6 6 7 7 8 9 ]);
M_.static_g1_sparse_colptr = int32([1 4 8 13 17 21 23 25 26 27 ]);
close all;
warning off;
M_.params(5) = 0.32;
ALPHA = M_.params(5);
M_.params(4) = 0.1;
DELTA = M_.params(4);
M_.params(6) = 0.42;
RHO = M_.params(6);
M_.params(3) = 2;
SIGMA = M_.params(3);
M_.params(9) = 0.0129;
ETA = M_.params(9);
M_.params(10) = 0.04;
r_int = M_.params(10);
M_.params(7) = 1.455;
OMEGA = M_.params(7);
M_.params(8) = 0.028;
PHI = M_.params(8);
M_.params(11) = 0.7442;
D_BAR = M_.params(11);
M_.params(2) = 0.000742;
PSI = M_.params(2);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
options_.irf = 50;
options_.nograph = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
save RBC_SOE_base.mat M_ oo_ options_;


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'RBC_SOE_TP3_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_SOE_TP3_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_SOE_TP3_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_SOE_TP3_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_SOE_TP3_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_SOE_TP3_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_SOE_TP3_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_SOE_TP3_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
